name: Deploy Mannarasala Admin API Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 010928200796.dkr.ecr.ap-south-1.amazonaws.com/masla-admin-api

    - name: Build and Push Docker Image
      run: |
        docker build -t masla-admin-api .
        docker tag masla-admin-api:latest 010928200796.dkr.ecr.ap-south-1.amazonaws.com/masla-admin-api:latest
        docker push 010928200796.dkr.ecr.ap-south-1.amazonaws.com/masla-admin-api:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: /home/ec2-user/deploy-admin-api.sh
